const XSL = `<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9">

  <xsl:output method="html" encoding="UTF-8" indent="yes"/>

  <xsl:template match="/">
    <html lang="en">
      <head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <title>Sitemap — LIZHENG.ME</title>
        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            background: #f8f9fa; color: #1a1a2e; line-height: 1.6;
          }
          .container { max-width: 960px; margin: 0 auto; padding: 2rem 1.5rem; }
          header { margin-bottom: 2rem; }
          h1 { font-size: 1.5rem; font-weight: 700; color: #1a1a2e; }
          .subtitle { color: #6c757d; font-size: 0.875rem; margin-top: 0.25rem; }
          .stats {
            display: flex; gap: 1.5rem; margin-top: 1rem;
            font-size: 0.8125rem; color: #6c757d;
          }
          .stats strong { color: #1a1a2e; font-weight: 600; }
          table {
            width: 100%; border-collapse: collapse;
            background: #fff; border-radius: 8px;
            overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.08);
          }
          thead { background: #f1f3f5; }
          th {
            text-align: left; padding: 0.75rem 1rem;
            font-size: 0.75rem; font-weight: 600;
            text-transform: uppercase; letter-spacing: 0.04em;
            color: #6c757d; border-bottom: 1px solid #e9ecef;
          }
          td {
            padding: 0.625rem 1rem; font-size: 0.8125rem;
            border-bottom: 1px solid #f1f3f5; vertical-align: middle;
          }
          tr:last-child td { border-bottom: none; }
          tr:hover td { background: #f8f9fa; }
          a { color: #4263eb; text-decoration: none; word-break: break-all; }
          a:hover { text-decoration: underline; }
          .priority { font-variant-numeric: tabular-nums; }
          .freq { text-transform: capitalize; }
          .date { color: #6c757d; white-space: nowrap; }
          footer {
            margin-top: 2rem; padding-top: 1rem;
            border-top: 1px solid #e9ecef;
            font-size: 0.75rem; color: #adb5bd;
          }
          @media (max-width: 640px) {
            .container { padding: 1rem; }
            th, td { padding: 0.5rem 0.625rem; font-size: 0.75rem; }
            .hide-mobile { display: none; }
          }
        </style>
      </head>
      <body>
        <div class="container">
          <header>
            <h1>&#x1f5fa; XML Sitemap</h1>
            <p class="subtitle">
              This sitemap is generated for search engines. You can also browse it here.
            </p>
            <div class="stats">
              <span><strong><xsl:value-of select="count(sitemap:urlset/sitemap:url)"/></strong> URLs</span>
            </div>
          </header>

          <table>
            <thead>
              <tr>
                <th>URL</th>
                <th class="hide-mobile">Priority</th>
                <th class="hide-mobile">Change Freq</th>
                <th>Last Modified</th>
              </tr>
            </thead>
            <tbody>
              <xsl:for-each select="sitemap:urlset/sitemap:url">
                <tr>
                  <td>
                    <a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a>
                  </td>
                  <td class="priority hide-mobile">
                    <xsl:value-of select="sitemap:priority"/>
                  </td>
                  <td class="freq hide-mobile">
                    <xsl:value-of select="sitemap:changefreq"/>
                  </td>
                  <td class="date">
                    <xsl:value-of select="substring(sitemap:lastmod, 1, 10)"/>
                  </td>
                </tr>
              </xsl:for-each>
            </tbody>
          </table>

          <footer>
            Generated by Firefly · <a href="/">LIZHENG.ME</a>
          </footer>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>`;

export function GET() {
  return new Response(XSL, {
    headers: {
      "Content-Type": "application/xslt+xml; charset=utf-8",
      "Cache-Control": "public, max-age=86400, s-maxage=86400",
    },
  });
}
